/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test void testRClass(){
        Restaurant sut = new Restaurant("Gamma","$$$$");
        System.out.println(sut.name + sut.pricing);
        Review blurb = new Review("good food","Armen",5);
        Review blurb2 = new Review("not good food","Steve",1);
        sut.addReview(blurb);
        sut.addReview(blurb2);
        System.out.println(sut.toString());
        System.out.println("cur rate"+sut.getRating());
    }
}
